// Dados consolidados por SEC com informações de Serviço, Fornecedor e Objeto
// Atualizado em: 06/05/2026

export interface Contrato {
  id: string;
  sec: string;
  servico?: string;
  fornecedor: string;
  objeto: string;
  mensal: number;
  anual: number;
}

export interface DespesaSemContrato {
  id: string;
  sec: string;
  servico: string;
  fornecedor: string;
  objeto: string;
  mensal: number;
  anual: number;
}

export const contratos: Contrato[] = [
  {
    id: "contrato-0",
    sec: "SEC -  AC",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 33624.83,
    anual: 403497.96,
  },
  {
    id: "contrato-1",
    sec: "SEC -  AL",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 58078.47,
    anual: 696941.64,
  },
  {
    id: "contrato-2",
    sec: "SEC -  AP",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 29712.84,
    anual: 356554.07999999996,
  },
  {
    id: "contrato-3",
    sec: "SEC -  AM",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 48851.3,
    anual: 586215.6,
  },
  {
    id: "contrato-4",
    sec: "SEC -  BA",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 34782.95,
    anual: 417395.4,
  },
  {
    id: "contrato-5",
    sec: "SEC -  CE",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 40213.84,
    anual: 482566.07999999996,
  },
  {
    id: "contrato-6",
    sec: "SEC -  ES",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 49173.06,
    anual: 590076.72,
  },
  {
    id: "contrato-7",
    sec: "SEC -  GO",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 41209.59,
    anual: 494515.07999999996,
  },
  {
    id: "contrato-8",
    sec: "SEC -  MA",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 43109.35,
    anual: 517312.19999999995,
  },
  {
    id: "contrato-9",
    sec: "SEC -  MT",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 24001.67,
    anual: 288020.04,
  },
  {
    id: "contrato-10",
    sec: "SEC -  MS",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 21851.02,
    anual: 262212.24,
  },
  {
    id: "contrato-11",
    sec: "SEC -  MG",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 33979.4,
    anual: 407752.8,
  },
  {
    id: "contrato-12",
    sec: "SEC-  PA",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 84825.47666666667,
    anual: 1017905.72,
  },
  {
    id: "contrato-13",
    sec: "SEC -  PB",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 125343.25,
    anual: 1504119.0,
  },
  {
    id: "contrato-14",
    sec: "SEC -  PR",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 27253.0,
    anual: 327036.0,
  },
  {
    id: "contrato-15",
    sec: "SEC -  PE",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 33594.369999999995,
    anual: 403132.44,
  },
  {
    id: "contrato-16",
    sec: "SEC-  PI",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 29678.149999999998,
    anual: 356137.8,
  },
  {
    id: "contrato-17",
    sec: "SEC -  RJ",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 324976.88,
    anual: 3899722.5600000005,
  },
  {
    id: "contrato-18",
    sec: "SEC -  RN",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 43708.41,
    anual: 524500.9199999999,
  },
  {
    id: "contrato-19",
    sec: "SEC -  RS",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 31535.590000000004,
    anual: 378427.08,
  },
  {
    id: "contrato-20",
    sec: "SEC -  RO",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 48629.380000000005,
    anual: 583552.56,
  },
  {
    id: "contrato-21",
    sec: "SEC -  RR",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 56087.19,
    anual: 996046.28,
  },
  {
    id: "contrato-22",
    sec: "SEC -  SC",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 31409.34,
    anual: 376912.07999999996,
  },
  {
    id: "contrato-23",
    sec: "SEC -  SP",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 90518.69,
    anual: 1086224.28,
  },
  {
    id: "contrato-24",
    sec: "SEC -  SE",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 24928.53,
    anual: 321342.36,
  },
  {
    id: "contrato-25",
    sec: "SEC -  TO",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 45312.15,
    anual: 543745.8,
  },
];

export const despesasSemContrato: DespesaSemContrato[] = [
  {
    id: "despesa-0",
    sec: "SEC -  AC",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 0,
    anual: 0,
  },
  {
    id: "despesa-1",
    sec: "SEC -  AL",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 2000.0,
    anual: 24000.0,
  },
  {
    id: "despesa-2",
    sec: "SEC -  AP",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 0,
    anual: 0,
  },
  {
    id: "despesa-3",
    sec: "SEC -  AM",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 8500.0,
    anual: 102000.0,
  },
  {
    id: "despesa-4",
    sec: "SEC -  BA",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 11000.0,
    anual: 132000.0,
  },
  {
    id: "despesa-5",
    sec: "SEC -  CE",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 0,
    anual: 0,
  },
  {
    id: "despesa-6",
    sec: "SEC -  ES",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 2400.0,
    anual: 28800.0,
  },
  {
    id: "despesa-7",
    sec: "SEC -  GO",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 0,
    anual: 0,
  },
  {
    id: "despesa-8",
    sec: "SEC -  MA",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 3108.84,
    anual: 37306.08,
  },
  {
    id: "despesa-9",
    sec: "SEC -  MT",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 14232.6,
    anual: 170791.2,
  },
  {
    id: "despesa-10",
    sec: "SEC -  MS",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 5625.0,
    anual: 67500.0,
  },
  {
    id: "despesa-11",
    sec: "SEC -  MG",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 12100.0,
    anual: 145200.0,
  },
  {
    id: "despesa-12",
    sec: "SEC-  PA",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 400.0,
    anual: 4800.0,
  },
  {
    id: "despesa-13",
    sec: "SEC -  PB",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 8224.75,
    anual: 98697.0,
  },
  {
    id: "despesa-14",
    sec: "SEC -  PR",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 2700.0,
    anual: 32400.0,
  },
  {
    id: "despesa-15",
    sec: "SEC -  PE",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 16782.91,
    anual: 201394.91999999998,
  },
  {
    id: "despesa-16",
    sec: "SEC-  PI",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 11002.4,
    anual: 132028.8,
  },
  {
    id: "despesa-17",
    sec: "SEC -  RJ",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 1851.54,
    anual: 22218.48,
  },
  {
    id: "despesa-18",
    sec: "SEC -  RN",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 3400.0,
    anual: 40800.0,
  },
  {
    id: "despesa-19",
    sec: "SEC -  RS",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 34417.2875,
    anual: 413007.44999999995,
  },
  {
    id: "despesa-20",
    sec: "SEC -  RO",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 8150.0,
    anual: 97800.0,
  },
  {
    id: "despesa-21",
    sec: "SEC -  RR",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 650.0,
    anual: 7800.0,
  },
  {
    id: "despesa-22",
    sec: "SEC -  SC",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 0,
    anual: 0,
  },
  {
    id: "despesa-23",
    sec: "SEC -  SP",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 47533.13,
    anual: 570397.5599999999,
  },
  {
    id: "despesa-24",
    sec: "SEC -  SE",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 14600.0,
    anual: 175200.0,
  },
  {
    id: "despesa-25",
    sec: "SEC -  TO",
    servico: "N/A",
    fornecedor: "N/A",
    objeto: "N/A",
    mensal: 14050.0,
    anual: 168600.0,
  },
];

export const secs = [
  "AL",
  "AM",
  "BA",
  "Diop-Estados",
  "ES",
  "MA",
  "MG",
  "MS",
  "MT",
  "PA",
  "PB",
  "PE",
  "PI",
  "PR",
  "RJ",
  "RN",
  "RO",
  "RR",
  "RS",
  "SE",
  "SEC-AC",
  "SEC-AL",
  "SEC-AM",
  "SEC-AP",
  "SEC-BA",
  "SEC-CE",
  "SEC-ES",
  "SEC-GO",
  "SEC-MA",
  "SEC-MG",
  "SEC-MS",
  "SEC-MT",
  "SEC-PA",
  "SEC-PB",
  "SEC-PE",
  "SEC-PI",
  "SEC-PR",
  "SEC-RJ",
  "SEC-RN",
  "SEC-RO",
  "SEC-RR",
  "SEC-RS",
  "SEC-SC",
  "SEC-SE",
  "SEC-SP",
  "SEC-TO",
  "SP",
  "TO",
];

// Calcular totais
export const totalMensalComContrato = contratos.reduce((acc, c) => acc + c.mensal, 0);
export const totalAnualComContrato = contratos.reduce((acc, c) => acc + c.anual, 0);
export const totalMensalSemContrato = despesasSemContrato.reduce((acc, d) => acc + d.mensal, 0);
export const totalAnualSemContrato = despesasSemContrato.reduce((acc, d) => acc + d.anual, 0);
export const totalMensal = totalMensalComContrato + totalMensalSemContrato;
export const totalAnual = totalAnualComContrato + totalAnualSemContrato;
