import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table";
import { useMemo, useState } from "react";
import { ChevronDown, ChevronUp, Search } from "lucide-react";
import { Input } from "@/components/ui/input";

interface Column<T> { key: keyof T; label: string; render?: (value: any, row: T) => React.ReactNode; format?: (value: any) => string; width?: string; sortable?: boolean; }
interface DataTableProps<T> { columns: Column<T>[]; data: T[]; searchable?: boolean; searchFields?: (keyof T)[]; title?: string; onRowClick?: (row: T) => void; }

export function DataTable<T extends Record<string, any>>({ columns, data, searchable = false, searchFields = [], title, onRowClick }: DataTableProps<T>) {
  const [searchTerm, setSearchTerm] = useState(""); const [sortKey, setSortKey] = useState<keyof T | null>(null); const [sortOrder, setSortOrder] = useState<"asc" | "desc">("asc");
  const filteredData = useMemo(() => !searchTerm || !searchFields.length ? data : data.filter(row => searchFields.some(field => String(row[field]).toLowerCase().includes(searchTerm.toLowerCase()))), [data, searchTerm, searchFields]);
  const sortedData = useMemo(() => !sortKey ? filteredData : [...filteredData].sort((a,b) => { const first = a[sortKey]; const second = b[sortKey]; const result = typeof first === "number" && typeof second === "number" ? first-second : String(first).localeCompare(String(second), "pt-BR", { sensitivity:"base" }); return sortOrder === "asc" ? result : -result; }), [filteredData, sortKey, sortOrder]);
  const toggleSort = (key: keyof T) => { if (sortKey === key) setSortOrder(value => value === "asc" ? "desc" : "asc"); else { setSortKey(key); setSortOrder("asc"); } };
  return <div className="space-y-4">{(title || searchable) && <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">{title && <h3 className="text-lg font-semibold text-[#172033]">{title}</h3>}{searchable && searchFields.length > 0 && <label className="relative block sm:w-72"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input placeholder="Buscar na tabela" value={searchTerm} onChange={event => setSearchTerm(event.target.value)} className="border-slate-200 bg-white pl-9 shadow-none" /></label>}</div>}<div className="overflow-x-auto rounded-xl border border-slate-200 bg-white shadow-[0_2px_12px_rgba(15,23,42,.04)]"><Table><TableHeader className="bg-[#f6f7f4]"><TableRow className="border-slate-200 hover:bg-transparent">{columns.map(column => <TableHead key={String(column.key)} style={{width:column.width}} onClick={() => column.sortable !== false && toggleSort(column.key)} className={`h-11 text-[11px] font-bold uppercase tracking-[.11em] text-slate-500 ${column.sortable !== false ? "cursor-pointer select-none hover:text-[#172033]" : ""}`}><span className="flex items-center gap-1.5">{column.label}{sortKey === column.key && (sortOrder === "asc" ? <ChevronUp className="h-3.5 w-3.5" /> : <ChevronDown className="h-3.5 w-3.5" />)}</span></TableHead>)}</TableRow></TableHeader><TableBody>{sortedData.length ? sortedData.map((row, index) => <TableRow key={String(row.id ?? index)} onClick={() => onRowClick?.(row)} className={`${onRowClick ? "cursor-pointer" : ""} border-slate-100 hover:bg-[#f8faf4]`}>{columns.map(column => <TableCell key={String(column.key)} className="py-3.5 text-sm text-slate-700">{column.render ? column.render(row[column.key], row) : column.format ? column.format(row[column.key]) : row[column.key]}</TableCell>)}</TableRow>) : <TableRow><TableCell colSpan={columns.length} className="py-12 text-center text-sm text-slate-500">Nenhum registro corresponde aos filtros aplicados.</TableCell></TableRow>}</TableBody></Table></div><p className="text-xs text-slate-500">{sortedData.length} de {data.length} registros exibidos</p></div>;
}
